# -*- coding: utf-8 -*-
"""B22BB016_MDLOPS_Ass5_Q2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uJsrxqLlvFAbgKtkDBeOqZTp7IJwSlIS
"""

!pip install -q adversarial-robustness-toolbox wandb torchvision matplotlib pandas torch

import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms
from torch.utils.data import DataLoader
from torchvision.models import resnet18
from art.estimators.classification import PyTorchClassifier
from art.attacks.evasion import FastGradientMethod
import wandb
import numpy as np
import matplotlib.pyplot as plt
import os
import pandas as pd

os.makedirs("weights", exist_ok=True)
os.makedirs("results", exist_ok=True)

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
BATCH_SIZE = 128
EPOCHS = 10 # ResNet18 trains fast, 10-15 epochs easily hits 72% on CIFAR-10
NUM_CLASSES = 10
EPSILONS = [0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3] # Perturbation strengths

def get_cifar10():
    # Only using ToTensor() to keep values in [0, 1] for easier attack clipping
    transform = transforms.Compose([transforms.ToTensor()])
    trainset = torchvision.datasets.CIFAR10(root='./data', train=True, download=True, transform=transform)
    testset = torchvision.datasets.CIFAR10(root='./data', train=False, download=True, transform=transform)
    trainloader = DataLoader(trainset, batch_size=BATCH_SIZE, shuffle=True, num_workers=2)
    testloader = DataLoader(testset, batch_size=BATCH_SIZE, shuffle=False, num_workers=2)
    return trainloader, testloader, testset.classes

def train_base_model(model, trainloader, testloader):
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=0.001)

    print("Training Base ResNet18 from scratch...")
    for epoch in range(EPOCHS):
        model.train()
        running_loss = 0.0
        for inputs, labels in trainloader:
            inputs, labels = inputs.to(DEVICE), labels.to(DEVICE)
            optimizer.zero_grad()
            outputs = model(inputs)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()
            running_loss += loss.item()

        # Quick eval
        model.eval()
        correct, total = 0, 0
        with torch.no_grad():
            for inputs, labels in testloader:
                inputs, labels = inputs.to(DEVICE), labels.to(DEVICE)
                outputs = model(inputs)
                _, predicted = outputs.max(1)
                total += labels.size(0)
                correct += predicted.eq(labels).sum().item()

        acc = 100. * correct / total
        print(f"Epoch {epoch+1}/{EPOCHS} | Loss: {running_loss/len(trainloader):.4f} | Test Acc: {acc:.2f}%")
        wandb.log({"base_epoch": epoch, "base_acc": acc, "base_loss": running_loss/len(trainloader)})

    return model

def fgsm_attack_scratch(image, epsilon, data_grad):
    # Collect the element-wise sign of the data gradient
    sign_data_grad = data_grad.sign()
    # Create the perturbed image by adjusting each pixel of the input image
    perturbed_image = image + epsilon * sign_data_grad
    # Adding clipping to maintain [0,1] range
    perturbed_image = torch.clamp(perturbed_image, 0, 1)
    return perturbed_image

def eval_fgsm_scratch(model, testloader, epsilon):
    correct = 0
    adv_examples = []
    model.eval()
    criterion = nn.CrossEntropyLoss()

    for data, target in testloader:
        data, target = data.to(DEVICE), target.to(DEVICE)
        data.requires_grad = True # Required to calculate gradient for image

        output = model(data)
        init_pred = output.max(1, keepdim=True)[1]

        loss = criterion(output, target)
        model.zero_grad()
        loss.backward()

        data_grad = data.grad.data
        perturbed_data = fgsm_attack_scratch(data, epsilon, data_grad)

        output = model(perturbed_data)
        final_pred = output.max(1, keepdim=True)[1]

        # Calculate accuracy
        correct += (final_pred.flatten() == target).sum().item()

        # Save a few examples for visualization
        if len(adv_examples) < 5:
            adv_ex = perturbed_data.squeeze().detach().cpu().numpy()
            orig_ex = data.squeeze().detach().cpu().numpy()
            adv_examples.append((init_pred[0].item(), final_pred[0].item(), orig_ex[0], adv_ex[0]))

    final_acc = correct / float(len(testloader.dataset))
    return final_acc, adv_examples

def run_task1():
    wandb.init(project="DL_Assignment_Q2", name="ResNet18_FGSM_Attacks")
    trainloader, testloader, classes = get_cifar10()

    # 1. Initialize and train ResNet18 from scratch (pretrained=False by default)
    model = resnet18(num_classes=NUM_CLASSES).to(DEVICE)
    model = train_base_model(model, trainloader, testloader)
    torch.save(model.state_dict(), "weights/q2_resnet18_base.pth")
    print("\nBase model trained and saved!")

    # 2. Setup IBM ART Classifier
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=0.001)
    art_classifier = PyTorchClassifier(
        model=model, clip_values=(0.0, 1.0), loss=criterion,
        optimizer=optimizer, input_shape=(3, 32, 32), nb_classes=NUM_CLASSES
    )

    results_table = []

    # 3. Loop through Epsilons (Perturbation Strengths)
    for eps in EPSILONS:
        print(f"\n--- Running attacks with Epsilon = {eps} ---")

        # A. Evaluate Scratch FGSM
        scratch_acc, scratch_examples = eval_fgsm_scratch(model, testloader, eps)

        # B. Evaluate ART FGSM
        art_attack = FastGradientMethod(estimator=art_classifier, eps=eps)

        art_correct = 0
        art_examples = []
        for data, target in testloader:
            data_np = data.cpu().numpy()
            adv_data_np = art_attack.generate(x=data_np)

            # Predict using PyTorch model to ensure fair comparison
            adv_data_tensor = torch.from_numpy(adv_data_np).to(DEVICE)
            with torch.no_grad():
                outputs = model(adv_data_tensor)
                _, preds = outputs.max(1)
                art_correct += preds.eq(target.to(DEVICE)).sum().item()

            if len(art_examples) < 5:
                art_examples.append(adv_data_np[0])

        art_acc = art_correct / len(testloader.dataset)

        print(f"Epsilon: {eps} | Scratch Acc: {scratch_acc*100:.2f}% | ART Acc: {art_acc*100:.2f}%")
        wandb.log({"epsilon": eps, "scratch_acc": scratch_acc, "art_acc": art_acc})

        results_table.append({
            "Epsilon (Strength)": eps,
            "Accuracy (Scratch)": f"{scratch_acc*100:.2f}%",
            "Accuracy (ART)": f"{art_acc*100:.2f}%"
        })

        # 4. Save qualitative images for Epsilon = 0.1 (You need this for README)
        if eps == 0.1:
            fig, axs = plt.subplots(3, 5, figsize=(15, 9))
            fig.suptitle('Qualitative Comparison (Epsilon = 0.1)', fontsize=16)

            for i in range(5):
                orig_class, adv_class, orig_img, adv_img_scratch = scratch_examples[i]
                adv_img_art = art_examples[i]

                # Original
                axs[0, i].imshow(np.transpose(orig_img, (1, 2, 0)))
                axs[0, i].set_title(f"Orig: {classes[orig_class]}")
                axs[0, i].axis('off')

                # Scratch Attack
                axs[1, i].imshow(np.transpose(adv_img_scratch, (1, 2, 0)))
                axs[1, i].set_title(f"Scratch: {classes[adv_class]}")
                axs[1, i].axis('off')

                # ART Attack
                axs[2, i].imshow(np.transpose(adv_img_art, (1, 2, 0)))
                axs[2, i].set_title(f"ART Attack")
                axs[2, i].axis('off')

            plt.tight_layout()
            plt.savefig('results/q2_fgsm_comparison.png')
            wandb.log({"Qualitative_Comparison": wandb.Image('results/q2_fgsm_comparison.png')})
            print("Saved comparison image to results/q2_fgsm_comparison.png")

    wandb.finish()

    print("\n--- FGSM RESULTS TABLE ---")
    print(pd.DataFrame(results_table).to_markdown(index=False))

if __name__ == "__main__":
    run_task1()

!pip install -q adversarial-robustness-toolbox wandb torchvision matplotlib pandas torch

import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms
from torch.utils.data import DataLoader, TensorDataset
from torchvision.models import resnet18, resnet34
from art.estimators.classification import PyTorchClassifier
from art.attacks.evasion import ProjectedGradientDescent, BasicIterativeMethod, FastGradientMethod
import wandb
import numpy as np
import os
import pandas as pd
import matplotlib.pyplot as plt

os.makedirs("weights", exist_ok=True)
os.makedirs("results", exist_ok=True)

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
BATCH_SIZE = 128
EPOCHS = 5 # Binary classification is relatively easy, 5 epochs is usually enough
NUM_CLASSES_BASE = 10
EPSILON = 0.05 # Standard strength for PGD/BIM

# To prevent Colab from timing out, we use a subset of CIFAR-10 to train the detector.
# 5000 clean + 5000 adversarial = 10,000 training images per detector.
NUM_TRAIN_SAMPLES = 5000
NUM_TEST_SAMPLES = 1000

def get_cifar10_loaders():
    transform = transforms.Compose([transforms.ToTensor()])
    trainset = torchvision.datasets.CIFAR10(root='./data', train=True, download=True, transform=transform)
    testset = torchvision.datasets.CIFAR10(root='./data', train=False, download=True, transform=transform)
    trainloader = DataLoader(trainset, batch_size=BATCH_SIZE, shuffle=True)
    testloader = DataLoader(testset, batch_size=BATCH_SIZE, shuffle=False)
    return trainloader, testloader

def load_victim_model():
    # Load the ResNet18 trained in Task 1
    model = resnet18(num_classes=NUM_CLASSES_BASE)
    try:
        model.load_state_dict(torch.load("weights/q2_resnet18_base.pth", map_location=DEVICE))
    except FileNotFoundError:
        print("CRITICAL ERROR: q2_resnet18_base.pth not found! Run Task 1 first.")
        raise
    model.to(DEVICE)
    model.eval()
    return model

def fgsm_attack_scratch(image, epsilon, data_grad):
    sign_data_grad = data_grad.sign()
    perturbed_image = image + epsilon * sign_data_grad
    return torch.clamp(perturbed_image, 0, 1)

def generate_detector_dataset(art_attack, dataloader, num_samples):
    clean_list = []
    adv_list = []
    total_generated = 0

    print(f"Generating {num_samples} adversarial images...")
    for data, target in dataloader:
        if total_generated >= num_samples:
            break

        # Keep clean data
        clean_list.append(data)

        # Generate adversarial data
        data_np = data.cpu().numpy()
        adv_data_np = art_attack.generate(x=data_np)
        adv_list.append(torch.from_numpy(adv_data_np))

        total_generated += len(data)
        if total_generated % 1000 < BATCH_SIZE: # Print progress
            print(f"Generated {total_generated}/{num_samples}...")

    # Concatenate lists into large tensors and slice to exact num_samples
    clean_tensor = torch.cat(clean_list)[:num_samples]
    adv_tensor = torch.cat(adv_list)[:num_samples]

    # Labels: 0 for Clean, 1 for Adversarial
    clean_labels = torch.zeros(num_samples, dtype=torch.long)
    adv_labels = torch.ones(num_samples, dtype=torch.long)

    # Combine and shuffle
    x_combined = torch.cat([clean_tensor, adv_tensor])
    y_combined = torch.cat([clean_labels, adv_labels])

    dataset = TensorDataset(x_combined, y_combined)
    return DataLoader(dataset, batch_size=BATCH_SIZE, shuffle=True)

def train_detector(trainloader, testloader, attack_name):
    print(f"\n--- Training ResNet34 Detector on {attack_name} dataset ---")

    # ResNet34 for Binary Classification (2 classes)
    model = resnet34(num_classes=2).to(DEVICE)
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=0.001)

    best_acc = 0.0
    for epoch in range(EPOCHS):
        model.train()
        running_loss = 0.0
        for inputs, labels in trainloader:
            inputs, labels = inputs.to(DEVICE), labels.to(DEVICE)
            optimizer.zero_grad()
            outputs = model(inputs)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()
            running_loss += loss.item()

        model.eval()
        correct, total = 0, 0
        with torch.no_grad():
            for inputs, labels in testloader:
                inputs, labels = inputs.to(DEVICE), labels.to(DEVICE)
                outputs = model(inputs)
                _, predicted = outputs.max(1)
                total += labels.size(0)
                correct += predicted.eq(labels).sum().item()

        acc = 100. * correct / total
        print(f"Epoch {epoch+1}/{EPOCHS} | Loss: {running_loss/len(trainloader):.4f} | Test Acc: {acc:.2f}%")

        # Log to WandB
        wandb.log({f"{attack_name}_epoch": epoch, f"{attack_name}_loss": running_loss/len(trainloader), f"{attack_name}_val_acc": acc})

        if acc > best_acc:
            best_acc = acc
            torch.save(model.state_dict(), f"weights/q2_resnet34_{attack_name}_detector.pth")

    return best_acc

def log_10_samples_to_wandb(victim_model, dataloader, art_classifier):
    print("\nGenerating 10 comparative samples for WandB logging...")

    # Get exactly 10 images
    data, target = next(iter(dataloader))
    data, target = data[:10].to(DEVICE), target[:10].to(DEVICE)

    # 1. Scratch FGSM
    data.requires_grad = True
    output = victim_model(data)
    loss = nn.CrossEntropyLoss()(output, target)
    victim_model.zero_grad()
    loss.backward()
    scratch_fgsm = fgsm_attack_scratch(data, EPSILON, data.grad.data).detach().cpu().numpy()

    # ART Attacks Setup
    data_np = data.detach().cpu().numpy()
    art_fgsm_gen = FastGradientMethod(estimator=art_classifier, eps=EPSILON)
    art_pgd_gen = ProjectedGradientDescent(estimator=art_classifier, eps=EPSILON, eps_step=0.01, max_iter=10)
    art_bim_gen = BasicIterativeMethod(estimator=art_classifier, eps=EPSILON, eps_step=0.01, max_iter=10)

    # Generate ART Attacks
    art_fgsm = art_fgsm_gen.generate(x=data_np)
    art_pgd = art_pgd_gen.generate(x=data_np)
    art_bim = art_bim_gen.generate(x=data_np)

    # Plotting
    fig, axs = plt.subplots(5, 10, figsize=(20, 10))
    fig.suptitle('Adversarial Attack Comparison (10 Samples)', fontsize=20)

    row_labels = ["Clean", "FGSM (Scratch)", "FGSM (ART)", "PGD (ART)", "BIM (ART)"]
    images = [data_np, scratch_fgsm, art_fgsm, art_pgd, art_bim]

    for row in range(5):
        axs[row, 0].set_ylabel(row_labels[row], fontsize=14, rotation=0, labelpad=50, ha='right')
        for col in range(10):
            axs[row, col].imshow(np.transpose(images[row][col], (1, 2, 0)))
            axs[row, col].set_xticks([])
            axs[row, col].set_yticks([])

    plt.tight_layout()
    plt.savefig('results/q2_10_samples_comparison.png')
    wandb.log({"All_Attacks_10_Samples": wandb.Image('results/q2_10_samples_comparison.png')})
    print("Logged 10 samples grid to WandB and saved to results folder.")
    plt.close()

def run_task2():
    wandb.init(project="DL_Assignment_Q2", name="ResNet34_Detectors")
    trainloader_base, testloader_base = get_cifar10_loaders()

    victim_model = load_victim_model()
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(victim_model.parameters(), lr=0.001)

    art_classifier = PyTorchClassifier(
        model=victim_model, clip_values=(0.0, 1.0), loss=criterion,
        optimizer=optimizer, input_shape=(3, 32, 32), nb_classes=NUM_CLASSES_BASE
    )

    # Log the 10 samples first
    log_10_samples_to_wandb(victim_model, testloader_base, art_classifier)

    results_table = []

    attacks_to_test = {
        "PGD": ProjectedGradientDescent(estimator=art_classifier, eps=EPSILON, eps_step=0.01, max_iter=10),
        "BIM": BasicIterativeMethod(estimator=art_classifier, eps=EPSILON, eps_step=0.01, max_iter=10)
    }

    for attack_name, attack_obj in attacks_to_test.items():
        print(f"\n========== PROCESSING {attack_name} ==========")
        # Generate mixed datasets (Clean=0, Adv=1)
        det_trainloader = generate_detector_dataset(attack_obj, trainloader_base, NUM_TRAIN_SAMPLES)
        det_testloader = generate_detector_dataset(attack_obj, testloader_base, NUM_TEST_SAMPLES)

        # Train and evaluate detector
        final_acc = train_detector(det_trainloader, det_testloader, attack_name)

        results_table.append({
            "Detector Type": f"ResNet-34 ({attack_name})",
            "Attack Processed": attack_name,
            "Detection Accuracy": f"{final_acc:.2f}%"
        })

    wandb.finish()

    print("\n--- DETECTOR PERFORMANCE TABLE (For Report) ---")
    print(pd.DataFrame(results_table).to_markdown(index=False))

if __name__ == "__main__":
    # Ensure q2_resnet18_base.pth is in the 'weights' folder before running!
    run_task2()