# -*- coding: utf-8 -*-
"""B22BB016_MDLOPS_Ass5_Q1_Optuna.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dqFsYZRt_AMxwIgWnY10diQCFQS5hp9C
"""

!pip install -q transformers peft optuna wandb torchvision optuna-integration

import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms
from torch.utils.data import DataLoader
from transformers import ViTForImageClassification
from peft import LoraConfig, get_peft_model
import optuna
import os

import wandb
from optuna.integration.wandb import WeightsAndBiasesCallback

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
BATCH_SIZE = 64
EPOCHS = 3 # Keep epochs low for Optuna to save time
NUM_CLASSES = 100
MODEL_NAME = "google/vit-base-patch16-224-in21k"

def get_dataloaders():
    transform = transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5])
    ])
    trainset = torchvision.datasets.CIFAR100(root='./data', train=True, download=True, transform=transform)
    testset = torchvision.datasets.CIFAR100(root='./data', train=False, download=True, transform=transform)
    trainloader = DataLoader(trainset, batch_size=BATCH_SIZE, shuffle=True, num_workers=2)
    testloader = DataLoader(testset, batch_size=BATCH_SIZE, shuffle=False, num_workers=2)
    return trainloader, testloader

def train_and_eval(model, trainloader, testloader):
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.AdamW(model.parameters(), lr=1e-3)

    for epoch in range(EPOCHS):
        model.train()
        for inputs, labels in trainloader:
            inputs, labels = inputs.to(DEVICE), labels.to(DEVICE)
            optimizer.zero_grad()
            outputs = model(inputs).logits
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()

    model.eval()
    correct, total = 0, 0
    with torch.no_grad():
        for inputs, labels in testloader:
            inputs, labels = inputs.to(DEVICE), labels.to(DEVICE)
            outputs = model(inputs).logits
            _, predicted = outputs.max(1)
            total += labels.size(0)
            correct += predicted.eq(labels).sum().item()

    return 100. * correct / total

def objective(trial):
    trainloader, testloader = get_dataloaders()

    # Let Optuna pick the hyperparameters
    r = trial.suggest_categorical("r", [2, 4, 8])
    alpha = trial.suggest_categorical("alpha", [2, 4, 8])

    print(f"\n--- Optuna Trial: Rank {r}, Alpha {alpha} ---")

    model = ViTForImageClassification.from_pretrained(MODEL_NAME, num_labels=NUM_CLASSES, ignore_mismatched_sizes=True)
    config = LoraConfig(r=r, lora_alpha=alpha, target_modules=["query", "key", "value"], lora_dropout=0.1, bias="none", modules_to_save=["classifier"])
    model = get_peft_model(model, config).to(DEVICE)

    accuracy = train_and_eval(model, trainloader, testloader)
    return accuracy

if __name__ == "__main__":


    wandb_kwargs = {
        "project": "DL_Assignment_Q1",
        "name": "Optuna_Hyperparameter_Search"
    }
    wandbc = WeightsAndBiasesCallback(wandb_kwargs=wandb_kwargs, as_multirun=True)

    # 2. Run the Study with the callback
    study = optuna.create_study(direction="maximize")

    print("\n========== Starting Optuna Search ==========")
    # Notice we added callbacks=[wandbc] here!
    study.optimize(objective, n_trials=5, callbacks=[wandbc])

    # 3. Print Final Results
    print("\n=== OPTUNA OPTIMIZATION COMPLETE ===")
    print("Best Trial:")
    print("  Value (Accuracy): ", study.best_trial.value)
    print("  Best Hyperparameters: ", study.best_trial.params)

    wandb.finish()